server:
  port: 8087

spring:
  datasource:
    username: root
    password: Zhuchkov777@yandex.ru
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
     hibernate: 12
    dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false

logging:
  level:
    root: INFO

indexing-settings:
  sites:
    #- url: https://skillbox.ru
    #  name: Skillbox
    #- url: https://lenta.ru
    #  name: Лента.ру
    - url: http://www.playback.ru
      name: Playback
      #- url: https://dombulgakova.ru
      #   name: Dom_Bulgakova
      # - url: https://ipfran.ru
    #  name: ipfran