server:
  port: 8087

spring:
  datasource:
    username: root
    password: Zhuchkov777@yandex.ru
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
   properties:
    hibernate:
       dialect: org.hibernate.dialect.MySQL8Dialect
   hibernate:
     ddl-auto: update
   show-sql: true
   open-in-view: false

logging:
  level:
    root: INFO

indexing-settings:
  sites:
    - url: http://www.playback.ru
      name: playback
    #️- url: https://lenta.ru
    # name: lenta
      #- url: http://radiomv.ru
      #name: radio
      #- url: https://dombulgakova.ru
      #name: dombulgakova
    - url: https://sendel.ru
      name: sendel
      #- url: https://volochek.life
      #  name: volochek
      #️- url: https://ipfran.ru/
      #️ name: ipfran
      #️ - url: https://dimonvideo.ru/
    #️   name: dimonvideo
    - url: https://nikoartgallery.com/
      name: nikoartgallery
    - url: https://et-cetera.ru/mobile/
      name: et-cetera
    - url: https://www.lutherancathedral.ru/
      name: lutherancathedral
      #️- url: https://www.svetlovka.ru/
      #️name: svetlovka

